const jsonServer = require('json-server')
var express = require('express')
const server = jsonServer.create()
const router = jsonServer.router('db.json')
const middlewares = jsonServer.defaults()

server.use(express.static('build'))
server.use(middlewares)
server.use(router)
server.listen(9001, () =>  console.log('\{^_^}/ hi!'))